introduction:
  class-item:
    a:
      -
        name: "Mike"
        lore:
          - "§l§2-------------------------"
          - "§6职业类型:：近 战"
          - "§5职业定位：战士"
          - "§3技能:"
          - "§b①技能：肾上腺素"
          - "§6介绍: 提高自己的心率以自己的速度和威力。"
          - "§6持续时间：5s，冷却 ： 15s ， 次数：6。"
          - "§b②技能：致残打击"
          - "§6介绍：迈克将灵能聚集于剑中,使下次攻击造成额外伤害和90%减速。"
          - "§6冷却：  15s ， 次数：3"
          - "§l§2-------------------------"
    d:
      -
        name: "§6Shrek"
        lore:
          - "§2-------------------------"
          - "§6职业类型:：近 战"
          - "§5职业定位：战士"
          - "§3技能:"
          - "①技能：原能修复"
          - "§6介绍: 史瑞克使用原能，加快自身和周围友军的血量回复速度。"
          - "§6治疗半径：5，冷却 ： 30s ， 次数：4。"
          - "§b②技能：格挡"
          - "§6介绍：史瑞克格挡下次攻击。"
          - "§6持续时间：0.6 s ，冷却：  6s ， 次数：无限"
          - "§2-------------------------"